### ISSUE TITLE
Help in Deployment And Access

### ISSUE THREAD

**Issue by samlasar** [ShelbyZ/node-ucwa#1]
I've downloaded this code and made it as a Node porject in Eclipse IDE.Could you please help me in deploying it in node server and also I want to know, how do I pass my SKYPE business credentials and login. Please help. Please treat this on High Priority. Thank you in Advance.

**Comment by ShelbyZ** [comment]
I'm not sure what you mean by 'deploying it in node server'.  i think you may be misunderstanding the goal of the project which is to allow proxying of requests to UCWA.  The intention is not to use this as a way to create a UCWA application in Node.  If you haven't already, I suggest taking a look at the [README](https://github.com/ShelbyZ/node-ucwa/blob/master/README.md) to get examples of usage.
